import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/main/Header";
import PageTransition from "@/components/main/PageTransition";
import StairTransition from "@/components/main/StairTransition";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jetBrainsMono.variable}>
      <body>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}

//export default function RootLayout({ children }) {
  //return (
    //<html lang="en" className={jetBrainsMono.variable} suppressHydrationWarning={true}>
      //<body suppressHydrationWarning={true}>
        //<Header />
        //<StairTransition />
        //<PageTransition>{children}</PageTransition>
      //</body>
    //</html>
  //);
//}